// flow-typed signature: e507e682b530fe653ee436f89466b621
// flow-typed version: <<STUB>>/@commitlint/config-angular_v^6.0.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/config-angular'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/config-angular' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@commitlint/config-angular/index' {
  declare module.exports: $Exports<'@commitlint/config-angular'>;
}
declare module '@commitlint/config-angular/index.js' {
  declare module.exports: $Exports<'@commitlint/config-angular'>;
}
