// flow-typed signature: a22652149d658430e092abef3402372b
// flow-typed version: <<STUB>>/eslint-import-resolver-jest_v^1.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-jest/__tests__/resolver.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-jest/__tests__/resolver.test.js' {
  declare module.exports: $Exports<'eslint-import-resolver-jest/__tests__/resolver.test'>;
}
declare module 'eslint-import-resolver-jest/index' {
  declare module.exports: $Exports<'eslint-import-resolver-jest'>;
}
declare module 'eslint-import-resolver-jest/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-jest'>;
}
