// flow-typed signature: 03471a8f1c40954e0dd9f74a894c6690
// flow-typed version: <<STUB>>/folder-module_v^2.0.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'folder-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'folder-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'folder-module/folder-module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'folder-module/folder-module.js' {
  declare module.exports: $Exports<'folder-module/folder-module'>;
}
declare module 'folder-module/index' {
  declare module.exports: $Exports<'folder-module'>;
}
declare module 'folder-module/index.js' {
  declare module.exports: $Exports<'folder-module'>;
}
