#! /bin/bash

set -ex

rm -rf storybook-static

docker run -it --rm \
  -e PERCY_TOKEN=$PERCY_TOKEN \
  -e PERCY_PROJECT=$PERCY_PROJECT \
  -e PERCY_BRANCH=$BRANCH_NAME \
  --user root -v $(pwd):/mnt/assets \
  react-ui-components \
  cp -r storybook-static/ /mnt/assets


npx percy-storybook
