#! /bin/bash

set -ex

rm -rf storybook-static

docker run -it --rm \
  -e PERCY_TOKEN=$PERCY_TOKEN \
  -e PERCY_PROJECT=$PERCY_PROJECT \
  -e PERCY_BRANCH=$BRANCH_NAME \
  --user root -v $(pwd):/mnt/assets \
  react-ui-components \
  cp -r storybook-static/ /mnt/assets


# Semaphore doesn't seem to use a good version of npm even when running node v8.x.x
# As such we will manually install npx
npm i -g npx

# Run the percy upload without having to install all the dependencies
npx percy-storybook
