#! /bin/bash

set -ex

# Run all tests agains the built result
docker run -it --rm \
  -e IS_CI=true \
  react-ui-components \
  ./scripts/ci/test-build

# Clean our local env
rm -rf dist
mkdir dist

# Copy the assets out of the docker container
docker run -it --rm \
  -v $(pwd):/mnt/assets \
  react-ui-components \
  cp -r dist/ /mnt/assets


# Release the krakken
npm run semantic-release
