#! /bin/bash

set -ex

# Run the setup script
# This means the docker container will be available to the node running the release job
. ./scripts/ci/setup

# Run all tests agains the built result
docker run -it --rm \
  -e IS_CI=true \
  react-ui-components \
  ./scripts/ci/test-build

# Clean our local env
rm -rf dist
mkdir dist

# Copy the assets out of the docker container
docker run -it --rm \
  --user root \
  -v $(pwd):/mnt/assets \
  react-ui-components \
  cp -r dist/ /mnt/assets


# Release the krakken
npx semantic-release
