#! /bin/bash

set -ex

# running tests agains dist/index.js will always fail because snapshots
# import names can clash, for example in src/index you will get:
# `import { Primitive } from 'src/components/Text'`

# where as agaist dist/index you will get
# `import { Primitive$2 } from 'src/components/Text'`

# as such, we delete all snapshots before testing dist/index
# so we get a clean green build

find . -name '*.snap' | xargs rm -rf

# Test the build result
npm run test -- --bail -u

